DATA_DIR = 'C:/Users/vikto/Downloads/bengaliai-cv19'
TRAIN_CSV = 'train.csv'
TEST_CSV = 'test.csv'
NB_DATASETS = 4
TRAIN_DATA_FILES = ['train_image_data_{}.parquet'.format(k) for k in range(NB_DATASETS)]
TEST_DATA_FILES = ['test_image_data_{}.parquet'.format(k) for k in range(NB_DATASETS)]
PICKLE_FILES = ['dataset{}.pkl'.format(k) for k in range(NB_DATASETS)]
CATEGORIES = ['grapheme_root', 'vowel_diacritic', 'consonant_diacritic']
OUTPUTS = [168, 11, 7]
BASE_SHAPE = (137, 236)
MEAN = (0.06922848809290576, )
STD = (0.20515700083327537, )
SIZE = 128
VALID_RATIO = 0.2
BS = 64
EPOCHS = 40
WEIGHT_DECAY = 0.01
WEIGHTS_PATH = 'best_model_all4.pth'
RESULT_GRAPH = 'results.png'
RECORDER_TEMPLATE1 = {'train': [0.0, 0.0, 0.0], 'valid': [0.0, 0.0, 0.0]}
RECORDER_TEMPLATE2 = {'train': 0.0, 'valid': 0.0}